### ISSUE TITLE
data parameter is nil

### ISSUE THREAD

**Issue by DreamBuddy** [AYJk/AYCheckVersion#3]
#11 Thread

NSInvalidArgumentException
data parameter is nil
}
0 CoreFoundation    **_exceptionPreprocess + 124
1 libobjc.A.dylib   objc_exception_throw + 56
2 CoreFoundation    -[NSException initWithCoder:]
3 Foundation    +[NSJSONSerialization JSONObjectWithData:options:error:] + 76
4 AYCheckVersion    __37-[AYCheckManager getInfoFromAppStore]_block_invoke + 116
5 CFNetwork ___75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32
6 CFNetwork ___49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 296
7 Foundation    ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 16
8 Foundation    -[NSBlockOperation main] + 96
9 Foundation    -[__NSOperationInternal _start:] + 604
10 Foundation   ___NSOQSchedule_f + 224
11 libdispatch.dylib    __dispatch_client_callout + 16
12 libdispatch.dylib    __dispatch_queue_drain + 864
13 libdispatch.dylib    __dispatch_queue_invoke + 464
14 libdispatch.dylib    __dispatch_root_queue_drain + 728
15 libdispatch.dylib    __dispatch_worker_thread3 + 112
16 libsystem_pthread.dylib  _pthread_wqthread + 1092
17 libsystem_pthread.dylib  start_wqthread + 4

您好，这里报错了 在解析 iTunesStore数据的时候 `getInfoFromAppStore` `NSDictionary *responseDic = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:nil];`这个方法没有 判断 error导致的，应该是 某些情况下 获取数据出现了问题。

非常感谢作者！

**Comment by AYJk** [comment]
应该是iTunes被墙导致的data为nil，现在做了修正，谢谢反馈。

**Comment by AtALoss** [comment]
跳转到APPStore后下载是一直弹出密码错误，但是我填的是正确的密码啊
