### ISSUE TITLE
您好，比较版本这块您看下

### ISSUE THREAD

**Issue by DreamBuddy** [AYJk/AYCheckVersion#4]
![image](https://cloud.githubusercontent.com/assets/3683368/18943554/fa404faa-8652-11e6-83c9-15a0e0e6f855.png)
您之前写的是 比较 版本号 是否 相同 来决定是否弹出alert，但是 Apple审核人员 拿到的 是 新版本，跟 AppleStore相比较 是不同的。。在审核期间 提示更新了，，被拒

**Comment by mxdhqm** [comment]
你的那个使用float方法比较是个错误的方法，如果版本号为1.1.1 之类的，那个方法无疑是不可取的

**Comment by AYJk** [comment]
@xmt0615 抱歉这个问题给你带来的困扰，之前是审核期间不会弹出提示，后来好像是发现那个方法在有些版本号更新的情况下会异常，所以替换了一次，现在已经修正了。

**Comment by DreamBuddy** [comment]
@AYJk @mxdhqm 感谢作者 感谢开源 感谢有你们
