### ISSUE TITLE
您好，这块我给修改了

### ISSUE THREAD

**Issue by mxdhqm** [AYJk/AYCheckVersion#5]
代码如下
`- (BOOL)isEqualByCompareLastVersion:(NSString *)lastVersion withCurrentVersion:(NSString *)currentVersion {
    NSArray *lastVersionArray = [lastVersion componentsSeparatedByString:@"."];
    NSArray *currentVersionArray = [currentVersion componentsSeparatedByString:@"."];
    for (int index = 0; index < lastVersionArray.count; index++) {
        if ([currentVersionArray[index] integerValue] < [lastVersionArray[index] integerValue]) {
            return NO;
        }
    }
    return YES;
}`
判断版本count不同直接返回有更新是个错误的做法，需要一个个比对，其次当前版本需低于最新版本才提示更新，而不是不同就提示更新

**Comment by AYJk** [comment]
@mxdhqm 非常感谢你的issue，你修正的这个我替换进去试过了，是有问题的，比如：线上版本为1.0.0，手中开发的版本为2.0，两者**componentsSeparatedByString**得到的数组元素个数是不等的，有越界问题。我现在修正了这个问题，自己测试是没问题的。再次感谢。

**Comment by mxdhqm** [comment]
恩恩，我忘了考虑新版本比老版本少的情况了，看了下你的代码，是把位数补齐了，感觉有点麻烦，我感觉只要比较相同的位数就可以了，后面多余的可以不用考虑，麻烦你测试下可行性
`
for (int index = 0; index < (lastVersionArray.count < currentVersionArray.count ? lastVersionArray.count : currentVersionArray.count); index++) {
        if ([currentVersionArray[index] integerValue] < [lastVersionArray[index] integerValue]) {
            return NO;
        }
    }
`
