### ISSUE TITLE
我發生點擊更新跳轉到AppStore後還是未更新的版本

### ISSUE THREAD

**Issue by momotw** [AYJk/AYCheckVersion#7]
會發生明明出現提醒版本更新，但跳轉到App Store還是未更新的版本嗎？

**Comment by AYJk** [comment]
@momotw 会的，虽然读取到的应用信息为最新的版本信息，但是AppStore可能不是最新版的情况。原因是CDN缓存的问题，过段时间就会正常。这个时间不确定，可能是马上就好，也可能需要半天或一天这样的。

**Comment by GouWeiBaCao** [comment]
我也发现这个 ,跳转到更新却还是旧版本,然后代码里面获取到的是旧版本 直接用浏览器打开地址下载到的js文件里面显示确实最新的版本号信息  不统一,有坑啊...

**Comment by GouWeiBaCao** [comment]
还有跟网络环境有关,4g获取的是最新的信息,但是wifi 获取下来的旧的版本信息

**Comment by AYJk** [comment]
处理了cdn缓存问题
