### ISSUE TITLE
关于提示更新延迟的问题

### ISSUE THREAD

**Issue by ChinaJackSion** [AYJk/AYCheckVersion#9]
新版应用已经审核通过好久了，可能由于cdn缓存的原因，访问到的版本信息还是旧的版本信息，而不是审核通过，马上就提示更新。如果在https://itunes.apple.com/lookup?country=cn&bundleId=bundleId&时间戳    后面拼接一个时间戳，就可以解决这个问题吧？

**Comment by AYJk** [comment]
@ChinaJackSion 感谢反馈，已经更新。
